FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_frontend.txt .

RUN pip3 install --no-cache-dir -r requirements_frontend.txt

COPY ./frontend ./frontend

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

# Run Streamlit app
ENTRYPOINT ["streamlit", "run", "./frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]