FROM python:3.13-slim

RUN apt-get update && apt-get install -y curl

WORKDIR /app

ADD https://astral.sh/uv/install.sh /uv-installer.sh

RUN sh /uv-installer.sh && rm /uv-installer.sh

ENV PATH="/root/.local/bin/:$PATH"

COPY pyproject.toml uv.lock* ./

RUN uv venv
RUN uv pip install -r pyproject.toml

# Copy your code
COPY ./data ./data
COPY ./backend ./backend

# Run with venv Python
RUN chmod +x ./backend/entrypoint.sh

ENTRYPOINT ["./backend/entrypoint.sh"]
